name: Lint

on:
  pull_request:
    branches: '**'
  push:
    branches: [dev, main]

# Cancel in-progress workflow runs on PRs when a new commit is pushed.
# Does not cancel any runs on `develop` or `master` branches.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  code:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run format:check

      - name: Run test
        run: npm run test
